# Generated by Django 5.2 on 2025-04-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
    ]
