# Generated by Django 5.2 on 2025-04-25 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0, help_text='cantidad actual en stock', validators=[django.core.validators.MinValueValidator(0)])),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='fecha de creación del stock')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='fecha de actualización del stock')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['product_id'],
            },
        ),
    ]
